name: PR Preview
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build-and-preview:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: quarto-dev/quarto-actions/setup@v2
      - uses: quarto-dev/quarto-actions/render@v2
        if: github.event.action != 'closed'
        with:
          to: html
          path: dapla-manual
      - name: Check if PR is still open
        id: check_pr
        run: |
          STATE=$(gh pr view ${{ github.event.pull_request.number }} --json state --jq .state)
          echo "state=$STATE" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy PR Preview
        if: steps.check_pr.outputs.state == 'OPEN'
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./dapla-manual/_site # The folder where Quarto renders the site
          token: ${{ secrets.GITHUB_TOKEN }}
